name: Cypress Tests

on: push

jobs:
 laravel-tests:
   runs-on: ubuntu-latest

   services:
     mysql:
       image: mysql:8.0
       ports:
         - 3306:3306
       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
       env:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: testdb
         MYSQL_USER: user
         MYSQL_PASSWORD: pass

   steps:
     - uses: actions/checkout@v2
     - name: Copy .env
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
     - name: Install Dependencies
       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
     - name: Generate key
       run: php artisan key:generate
     - name: Directory Permissions
       run: chmod -R 777 storage bootstrap/cache
     - name: Wait for MySQL
       run: sleep 15
     - name: Execute tests (Unit and Feature tests) via PHPUnit
       env:
         DB_CONNECTION: mysql
         DB_HOST: 127.0.0.1
         DB_PORT: 3306
         DB_DATABASE: testdb
         DB_USERNAME: root
         DB_PASSWORD: password
       run: ./vendor/bin/pest

 cypress-run:
   needs: laravel-tests
   runs-on: ubuntu-22.04
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
         build: npm run build
         start: npm start
